name: Documentation
on:
  push:
    paths:
      - 'owl/**'
      - 'docs/**'
      - '.github/**'

jobs:
  handbook:
    name: NEEM Handbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        uses: docker://blang/latex:ubuntu
        env:
          TEXINPUTS: "/github/workspace/template:"
        with:
          args: make -f ./docs/NEEM-handbook/Makefile

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: NEEM Handbook
          path: ./docs/NEEM-handbook/main.pdf
