name: Consistency
on:
  push:
    paths:
      - '**'
      - '!docs/**'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
  release:
    types: [created]
    paths:
      - '**'
      - '!docs/**'

jobs:
  pitfalls:
    name: OOPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Compile
        uses: docker://swipl:8.0.3
        with:
          SOMA_VERSION: current
          args: swipl -f prolog/uglify.pl -t uglify
      
      - name: Setup Python
        uses: actions/setup-python@v2
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Find pitfalls
        run: sudo ./scripts/oops.py $GITHUB_WORKSPACE/build/SOMA.owl $GITHUB_WORKSPACE/build

      - name: Upload pitfalls
        uses: actions/upload-artifact@v1
        with:
          name: OOPS Results
          path: ./build/oops.xml
  
  consistency:
    name: Consistency
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Compile
        uses: docker://swipl:8.0.3
        with:
          SOMA_VERSION: current
          args: swipl -f prolog/uglify.pl -t uglify

      - name: HermiT
        uses: ./.github/actions/hermit
        with:
          args: ./build/SOMA.owl

      - name: Print HermiT output
        run: cat ./hermit.output
        if: always()

      - name: Evaluate HermiT output
        if: success()
        uses: docker://python:3.7.6-slim
        with:
          args: python ./scripts/hermit_test.py -o ./owl/hermit.html ./hermit.output

